{% set name = "agnpy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e73ab7ede7c1eb54d1981a3d852fa3739e4265db3d190d08432510e644c37dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - astropy >=4
    - matplotlib-base
    - numpy >=1.17
    - python >=3.8
    - scipy >=1.2

test:
  imports:
    - agnpy

about:
  home: https://github.com/cosimoNigro/agnpy
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Modelling jetted Active Galactic Nuclei radiative processes with python
  description: |
    agnpy focuses on the numerical computation of the photon spectra produced
    by leptonic radiative processes in jetted Active Galactic Nuclei (AGN).
  doc_url: https://agnpy.readthedocs.io/
  dev_url: https://github.com/cosimoNigro/agnpy

extra:
  recipe-maintainers:
    - mwcraig
