{% set name = "agnpy" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 445b9ddffc61691c53c309bdaf6f44ac609f0f227faa55f16f8e69e6a2a0aa4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - astropy >=4
    - matplotlib-base
    - numpy >=1.17
    - python >=3.6
    - scipy >=1.2

test:
  imports:
    - agnpy

about:
  home: https://github.com/cosimoNigro/agnpy
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Modelling jetted Active Galactic Nuclei radiative processes with python
  description: |
    agnpy focuses on the numerical computation of the photon spectra produced
    by leptonic radiative processes in jetted Active Galactic Nuclei (AGN).
  doc_url: https://agnpy.readthedocs.io/
  dev_url: https://github.com/cosimoNigro/agnpy

extra:
  recipe-maintainers:
    - mwcraig
